name: Create Binary Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.4.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm i -g pnpm
      - run: npm i -g yarn
      - run: pnpm i
      - run: pnpm run build

      - name: Setup release
        run: mkdir release

      - name: Move dists to release
        run: |
          cp apps/server/package.json build
          cp -r apps/server/dist release/server
          cp -r apps/web/out release/server/client
      - name: Upload artifant
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: release
